swagger: '2.0'
info:
  description: 'This is an API documentation for Home Accounting software. This software
    will be developed as a platform and provide User Interface through an android based Mobile app'
  version: 1.0.0
  title: Home Accounting
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: aapandit@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: 'aws'
basePath: /v2
tags:
  - name: accounts
    description: Everything about household accounts
    externalDocs:
      description: Find out more
      url: 'http://swagger.io'
schemes:
  - http
paths:
  /accounts:
    post: 
      tags:
        - accounts
      summary: Add a new account
      description: ''
      operationId: addAccount
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      parameters:
        - in: body
          name: body
          description: Account object that needs to be added for accounting
          required: true
          schema:
            $ref: '#/definitions/Account'
      responses:
        '405':
          description: Invalid input
    put:
      tags:
        - accounts
      summary: Update an existing account
      description: ''
      operationId: updateAccount
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      parameters:
        - in: body
          name: body
          description: Acocunt object that needs to be added for Accounting
          required: true
          schema:
            $ref: '#/definitions/Account'
      responses:
        '400':
          description: Invalid ID supplied
        '404':
          description: Account not found
        '405':
          description: Validation exception
  '/accounts/{accountId}':
    get:
      tags:
        - accounts
      summary: Find account by ID
      description: Returns a single account
      operationId: getAccountById
      produces:
        - application/xml
        - application/json
      parameters:
        - name: accountId
          in: path
          description: ID of account to return
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Account'
        '400':
          description: Invalid ID supplied
        '404':
          description: Account not found
    delete:
      tags:
        - accounts
      summary: Deletes an account
      description: ''
      operationId: deleteAccount
      produces:
        - application/xml
        - application/json
      parameters:
        - name: api_key
          in: header
          required: false
          type: string
        - name: accountId
          in: path
          description: Account id to delete
          required: true
          type: integer
          format: int64
      responses:
        '400':
          description: Invalid ID supplied
        '404':
          description: Account not found
definitions:
  Account:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
        example: Ram-Wallet
      type:
        type: string
        enum:
          - sb
          - fd
          - wl  
      description:
        type: string
      status:
        type: string
        enum:
          - created
          - inactive
          - active
    xml:
      name: Account
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
