swagger: '2.0'
info:
  description: 'This is an API documentation for Home Accounting software. This software
    will be developed as a platform and provide User Interface through an android based Mobile app'
  version: 1.0.0
  title: Home Accounting
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: aapandit@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: 'aws'
basePath: /v2
tags:
  - name: transactions
    description: Everything about household accounts
    externalDocs:
      description: Find out more
      url: 'http://swagger.io'
schemes:
  - http
paths:
  /transactions:
    post: 
      tags:
        - transactions
      summary: Add a new transaction
      description: ''
      operationId: addTransaction
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      parameters:
        - in: body
          name: body
          description: Transaction object that needs to be added to the account
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      responses:
        '405':
          description: Invalid input
    get:
      tags:
        - transactions
      summary: Finds all transactions
      description: Returns a single account
      operationId: getAllTransactions
      produces:
        - application/xml
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Invalid ID supplied
        '404':
          description: Account not found
  /transactions/{transactionId}:
    delete:
      tags:
        - transactions
      summary: Deletes a transaction
      description: ''
      operationId: deleteTransaction
      produces:
        - application/xml
        - application/json
      parameters:
        - name: transactionId
          in: path
          description: Transaction id to delete
          required: true
          type: integer
          format: int64
      responses:
        '400':
          description: Invalid ID supplied
        '404':
          description: Transaction not found
definitions:
  Transaction:
    type: object
    properties:
      id:
        type: string
      accountId:
        type: integer
        format: int64
      dateTime: 
        type: string
        format: date-time
      amount:
        type: number
        format: double
      type:
        type: string
        enum:
          - credit
          - debit
      status:
        type: string
        enum:
          - success
          - fail
    xml:
      name: Transaction
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
